scripts/install-*: Allow both data.pak variants for all localisations and always use binary mode for md5sum.

diff --git a/scripts/install-gog b/scripts/install-gog
--- a/scripts/install-gog
+++ b/scripts/install-gog
@@ -21,8 +21,9 @@ here="$(pwd)"
 echo "Installing Arx Fatalis GOG.com data from \"$setupfile\" to \"$destdir\".
 "
 
-[ -f "$here/install-common" ] || die "Missing install-common script."
-. "$here/install-common"
+[ -f "$here/install-verify" ] || die "Missing install-verify script."
+install_verify_sourced=1
+. "$here/install-verify"
 
 # Check for required commands
 
@@ -33,7 +34,7 @@ innoextract=`which innoextract 2> /dev/null`
 
 # Verify input file
 
-checksum="$("$md5sum" "$setupfile" | sed 's/ .*//')"
+checksum="$("$md5sum" -b "$setupfile" | sed 's/ .*//')"
 expected='0dd8ec13c10146db1a741258b624040a'
 if [ "$checksum" = "$expected" ] 
 	then echo "Checksum matched."
@@ -74,4 +75,5 @@ rm -rf "$tempdir"
 
 # Verify installed files
 
-verify_checksums "$destdir" "$@"
+detect_language "$destdir"
+verify_checksums "$destdir"
