scripts: Improve portability of the install scripts.

diff --git a/scripts/install-demo b/scripts/install-demo
--- a/scripts/install-demo
+++ b/scripts/install-demo
@@ -1,14 +1,16 @@
 #!/bin/sh
 
-function die() {
+die() {
 	echo "$@" >&2
 	exit 1
 }
 
-[ "$1" == "--help" ] || [ "$1" == "-h" ] || zipfile="$(readlink -f "$1")"
+# Handle arguments
+
+[ "$1" = "--help" ] || [ "$1" = "-h" ] || zipfile="$(readlink -f "$1")"
 [ "$zipfile" != "" ] || die "Usage: install-demo path/to/arx_demo_english.zip [output_dir]"
 
-if [ "$2" == "" ]
+if [ "$2" = "" ]
 	then destdir="$(pwd)"
 	else destdir="$(readlink -f "$2")"
 fi
@@ -16,8 +18,10 @@ fi
 cd "$(dirname "$0")"
 here="$(pwd)"
 
-echo "Installing Arx Fatalis demo data from \"$zipfile\" to \"$destdir\"."
-echo
+echo "Installing Arx Fatalis demo data from \"$zipfile\" to \"$destdir\".
+"
+
+# Check for required commands
 
 cabextract=`which cabextract 2> /dev/null`
 unzip=`which unzip 2> /dev/null`
@@ -33,27 +37,31 @@ md5sum=`which md5sum 2> /dev/null`
 
 [ -f "$zipfile" ] || die "Input file \"$zipfile\" not found."
 
-function extract_cab() {
+extract_cab() {
 	"$cabextract" "$1"
 }
 
-function extract_zip() {
+extract_zip() {
 	if [ -f "$unzip" ]
 		then "$unzip" "$1"
 		else "$bsdtar" xvf "$1"
 	fi
 }
 
+# Verify input file
+
 if [ -f "$md5sum" ]
-	then 
+	then
 		checksum="$(md5sum "$zipfile" | sed 's/ .*//')"
 		expected='3c59a5799e1237b1b181c96e8c09155a'
-		if [ "$checksum" == "$expected" ] 
+		if [ "$checksum" = "$expected" ] 
 			then echo "Checksum matched."
 			else echo "Got checksum $checksum, expected $expected."
 		fi
 	else echo "Missing md5sum, cannot verify that you have the correct archive."
 fi
+
+# Prepare output and temp dirs
 
 mkdir -p "$destdir" || exit 1
 
@@ -63,16 +71,20 @@ rm -rf "$tempdir" 2> /dev/null
 mkdir "$tempdir" || exit 1
 cd "$tempdir" || exit 1
 
+# Extract files
+
 extract_zip "$zipfile"
 
 extract_cab Setup1.cab
 extract_cab Setup2.cab
 extract_cab Setup3.cab
 
-function doinstall() {
-	mv -fv "$tempdir/$1" "$destdir/$2"
-	chmod "--reference=$destdir" "$destdir/$2" &> /dev/null
-	chmod -x "$destdir/$2" &> /dev/null
+# Install required files
+
+doinstall() {
+	mv -fv "$1" "$destdir/$2"
+	chmod "--reference=$destdir" "$destdir/$2" > /dev/null 2>&1
+	chmod -x "$destdir/$2" > /dev/null 2>&1
 }
 
 mkdir -pv "$destdir/misc"
@@ -84,30 +96,29 @@ doinstall "data.pak" "data.pak"
 doinstall "SFX.pak" "sfx.pak"
 doinstall "SPEECH.pak" "speech.pak"
 
+# Cleanup temporary files
+
 rm -rf "$tempdir"
 
-echo
-echo "Done:"
+echo "
+Done:"
 
-checksums_demo="$(cat "$here/data-demo.md5")"
+# Verify installed files
 
-if [ -f "$md5sum" ]
-	then
-		checksums=`cd "$destdir" \
-			&& "$md5sum" data2.pak data.pak loc.pak misc/arx.ttf misc/logo.bmp sfx.pak speech.pak`
-		if [ "$checksums" == "$checksums_demo" ]
-			then echo "Checksum match."
-			else
-				echo >&2
-				echo "Checksum mismatch, expected" >&2
-				echo >&2
-				echo "$checksums_demo" >&2
-				echo >&2
-				echo " got" >&2
-				echo >&2
-				echo "$checksums" >&2
-				exit 1
-		fi
-	else
-		echo "Could not verify checksum, md5 not available."
-fi
+[ -f "$md5sum" ] || ( echo "Could not verify checksum, md5sum not available." ; exit )
+
+cd "$destdir"
+checksums=`"$md5sum" data2.pak data.pak loc.pak misc/arx.ttf misc/logo.bmp sfx.pak speech.pak`
+
+checksums_demo="$(cat "$here/data-demo.md5")" || die "Could not read data-demo.md5"
+
+[ "$checksums" = "$checksums_demo" ] || die "
+Checksum mismatch, expected
+
+$checksums_demo
+
+ got
+
+$checksums"
+
+echo "Checksum match." 
diff --git a/scripts/install-gog b/scripts/install-gog
--- a/scripts/install-gog
+++ b/scripts/install-gog
@@ -1,14 +1,16 @@
 #!/bin/sh
 
-function die() {
+die() {
 	echo "$@" >&2
 	exit 1
 }
 
-[ "$1" == "--help" ] || [ "$1" == "-h" ] || setupfile="$(readlink -f "$1")"
+# Handle arguments
+
+[ "$1" = "--help" ] || [ "$1" = "-h" ] || setupfile="$(readlink -f "$1")"
 [ "$setupfile" != "" ] || die "Usage: install-demo path/to/setup_arx_fatalis.exe [output_dir]"
 
-if [ "$2" == "" ]
+if [ "$2" = "" ]
 	then destdir="$(pwd)"
 	else destdir="$(readlink -f "$2")"
 fi
@@ -16,8 +18,10 @@ fi
 cd "$(dirname "$0")"
 here="$(pwd)"
 
-echo "Installing Arx Fatalis GOG.com data from \"$setupfile\" to \"$destdir\"."
-echo
+echo "Installing Arx Fatalis GOG.com data from \"$setupfile\" to \"$destdir\".
+"
+
+# Check for required commands
 
 innoextract=`which innoextract 2> /dev/null`
 md5sum=`which md5sum 2> /dev/null`
@@ -25,16 +29,20 @@ md5sum=`which md5sum 2> /dev/null`
 [ -f "$innoextract" ] \
 	|| die "Please install innoextract (http://innoextract.constexpr.org/)"
 
+# Verify input file
+
 if [ -f "$md5sum" ]
-	then 
+	then
 		checksum="$(md5sum "$setupfile" | sed 's/ .*//')"
 		expected='0dd8ec13c10146db1a741258b624040a'
-		if [ "$checksum" == "$expected" ] 
+		if [ "$checksum" = "$expected" ] 
 			then echo "Checksum matched."
 			else echo "Got checksum $checksum, expected $expected."
 		fi
 	else echo "Missing md5sum, cannot verify that you have the correct archive."
 fi
+
+# Prepare output and temp dirs
 
 mkdir -p "$destdir" || exit 1
 
@@ -44,84 +52,86 @@ rm -rf "$tempdir" 2> /dev/null
 mkdir "$tempdir" || exit 1
 cd "$tempdir" || exit 1
 
+# Extract files
+
 "$innoextract" --lowercase "$setupfile"
 
-files=(
-	data2.pak
-	data.pak
-	graph/interface/misc/arkane.bmp
-	graph/interface/misc/quit1.bmp
-	graph/obj3d/textures/fixinter_barrel.jpg
-	graph/obj3d/textures/fixinter_bell.bmp
-	graph/obj3d/textures/fixinter_metal_door.jpg
-	graph/obj3d/textures/fixinter_public_notice.bmp
-	graph/obj3d/textures/item_bread.bmp
-	graph/obj3d/textures/item_club.jpg
-	graph/obj3d/textures/item_long_sword.jpg
-	graph/obj3d/textures/item_mauld_sabre.jpg
-	graph/obj3d/textures/item_mauldsword.jpg
-	graph/obj3d/textures/item_mirror.jpg
-	graph/obj3d/textures/item_ring_casting.bmp
-	graph/obj3d/textures/item_rope.bmp
-	graph/obj3d/textures/item_spell_sheet.jpg
-	graph/obj3d/textures/item_torch2.jpg
-	graph/obj3d/textures/item_torch.jpg
-	graph/obj3d/textures/item_zohark.bmp
-	graph/obj3d/textures/l7_dwarf_[wood]_board08.jpg
-	graph/obj3d/textures/l7_dwarf_[wood]_board80.jpg
-	graph/obj3d/textures/npc_dog.bmp
-	graph/obj3d/textures/npc_pig.bmp
-	graph/obj3d/textures/npc_pig_dirty.bmp
-	graph/obj3d/textures/npc_rat_base.bmp
-	graph/obj3d/textures/npc_rat_base_cm.bmp
-	graph/obj3d/textures/npc_worm_body_part1.jpg
-	graph/obj3d/textures/npc_worm_body_part2.bmp
-	graph/obj3d/textures/[wood]_light_door.jpg
-	loc.pak
-	misc/arx_default.ttf
-	misc/arx_russian.ttf
-	misc/arx_taiwanese.ttf
-	misc/arx.ttf
-	misc/logo.avi
-	misc/logo.bmp
-	sfx.pak
-	speech.pak
-)
+# Install required files
+
+set -- \
+	"data2.pak" \
+	"data.pak" \
+	"graph/interface/misc/arkane.bmp" \
+	"graph/interface/misc/quit1.bmp" \
+	"graph/obj3d/textures/fixinter_barrel.jpg" \
+	"graph/obj3d/textures/fixinter_bell.bmp" \
+	"graph/obj3d/textures/fixinter_metal_door.jpg" \
+	"graph/obj3d/textures/fixinter_public_notice.bmp" \
+	"graph/obj3d/textures/item_bread.bmp" \
+	"graph/obj3d/textures/item_club.jpg" \
+	"graph/obj3d/textures/item_long_sword.jpg" \
+	"graph/obj3d/textures/item_mauld_sabre.jpg" \
+	"graph/obj3d/textures/item_mauldsword.jpg" \
+	"graph/obj3d/textures/item_mirror.jpg" \
+	"graph/obj3d/textures/item_ring_casting.bmp" \
+	"graph/obj3d/textures/item_rope.bmp" \
+	"graph/obj3d/textures/item_spell_sheet.jpg" \
+	"graph/obj3d/textures/item_torch2.jpg" \
+	"graph/obj3d/textures/item_torch.jpg" \
+	"graph/obj3d/textures/item_zohark.bmp" \
+	"graph/obj3d/textures/l7_dwarf_[wood]_board08.jpg" \
+	"graph/obj3d/textures/l7_dwarf_[wood]_board80.jpg" \
+	"graph/obj3d/textures/npc_dog.bmp" \
+	"graph/obj3d/textures/npc_pig.bmp" \
+	"graph/obj3d/textures/npc_pig_dirty.bmp" \
+	"graph/obj3d/textures/npc_rat_base.bmp" \
+	"graph/obj3d/textures/npc_rat_base_cm.bmp" \
+	"graph/obj3d/textures/npc_worm_body_part1.jpg" \
+	"graph/obj3d/textures/npc_worm_body_part2.bmp" \
+	"graph/obj3d/textures/[wood]_light_door.jpg" \
+	"loc.pak" \
+	"misc/arx_default.ttf" \
+	"misc/arx_russian.ttf" \
+	"misc/arx_taiwanese.ttf" \
+	"misc/arx.ttf" \
+	"misc/logo.avi" \
+	"misc/logo.bmp" \
+	"sfx.pak" \
+	"speech.pak"
 
 mkdir -pv "$destdir/graph/interface/misc"
 mkdir -pv "$destdir/graph/obj3d/textures"
 mkdir -pv "$destdir/misc"
 
-for f in "${files[@]}" ; do
-	mv -fv "$tempdir/app/$f" "$destdir/$f"
-	chmod "--reference=$destdir" "$destdir/$2" &> /dev/null
-	chmod -x "$destdir/$2" &> /dev/null
+for f in "$@" ; do
+	mv -fv "app/$f" "$destdir/$f"
+	chmod "--reference=$destdir" "$destdir/$f" > /dev/null 2>&1
+	chmod -x "$destdir/$f" > /dev/null 2>&1
 done
+
+# Cleanup temporary files
 
 rm -rf "$tempdir"
 
-echo
-echo "Done:"
+echo "
+Done:"
 
-checksums_en="$(cat "$here/data-en.md5")"
+# Verify installed files
 
-if [ -f "$md5sum" ]
-	then
-		checksums=`cd "$destdir" \
-			&& "$md5sum" "${files[@]}"`
-		if [ "$checksums" == "$checksums_en" ]
-			then echo "Checksum match."
-			else
-				echo >&2
-				echo "Checksum mismatch, expected" >&2
-				echo >&2
-				echo "$checksums_en" >&2
-				echo >&2
-				echo " got" >&2
-				echo >&2
-				echo "$checksums" >&2
-				exit 1
-		fi
-	else
-		echo "Could not verify checksum, md5 not available."
-fi
+[ -f "$md5sum" ] || ( echo "Could not verify checksum, md5sum not available." ; exit )
+
+cd "$destdir"
+checksums=`"$md5sum" "$@"`
+
+checksums_en="$(cat "$here/data-en.md5")" || die "Could not read data-en.md5"
+
+[ "$checksums" = "$checksums_en" ] || die "
+Checksum mismatch, expected
+
+$checksums_en
+
+ got
+
+$checksums"
+
+echo "Checksum match."
